### ISSUE TITLE
运行yarn serve报错Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by hello-lun** [vuejs/vue-cli-plugin-vue-next#29] opened 2020-05-03 15:37 UTC
### 运行yarn serve报错
使用vue create vue3搭建了项目，然后使用vue add vue-next，再运行yarn serve打开网页就报以下错误

vue-cli版本：4.3.1

![image](https://user-images.githubusercontent.com/34638158/80918302-d4061280-8d96-11ea-902d-8808b4cc484b.png)

**Comment by xinpingwang** [comment] 2020-05-03 21:36
**Assume you have install Vue devtools extensions to your browser, and use vuex in your project** 

## Solution
1. Make following changes to your package.json.
![image](https://user-images.githubusercontent.com/41824968/80925630-fb270900-8dc3-11ea-878b-55a6c6d67c37.png)

2. (or) disable Vue devtools

## Problem
I encountered same problem yesterday, This problem is caused by vuejs/vue-next#1107 and introduce in https://github.com/vuejs/vue-next/releases/tag/v3.0.0-beta.7.

when the project start, vuex will [emit](https://github.com/vuejs/vuex/blob/a39d0767e4041cdd5cf8050774106c01d39024e0/src/plugins/devtool.js#L13) an `vuex:init` event to vue devtools, and then vue devtools will try to [make a clone](https://github.com/vuejs/vue-devtools/blob/2b0214f1bda2c36a5eb4e8d0c22148c146d55ee3/packages/app-backend/src/hook.js#L101) of the current vuex state, causes [`getCleanClone`](https://github.com/vuejs/vue-devtools/blob/2b0214f1bda2c36a5eb4e8d0c22148c146d55ee3/packages/app-backend/src/hook.js#L213) to be invoked. the `getCleanClone` function, will read `store.state.__proto__`.

this issue is fixed by https://github.com/vuejs/vue-next/commit/6be2b73f8aeb26be72eab22259c8a513b59b910f, so you can lock vue version to v3.0.0-beta.6, and wait v3.0.0-beta.8 to be released.

**Comment by hello-lun** [comment] 2020-05-04 15:54
> vuejs/vue-next@6be2b73

thanks, Problem has been solved

**Closed** 2020-05-08 08:55 UTC
